# Generated by Django 5.0.4 on 2024-06-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimHub",
            fields=[
                ("hub_id", models.AutoField(primary_key=True, serialize=False)),
                ("shortcode", models.CharField(max_length=10)),
                ("name_en", models.CharField(max_length=255)),
                ("name_ar", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("governorate_id", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
